name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

# todo: удалить, когда пакет geolocator обновит свои зависимости
dependency_overrides:
  uuid: ^4.1.0

dependencies:
  flutter:
    sdk: flutter
#  flutter_bloc: ^8.1.3
  loggy: ^2.0.3
  weather_pack: ^1.0.0
  path: ^1.8.3
  http: ^1.1.0
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  geolocator: ^10.1.0
  #firebase_core: ^2.15.0
  #firebase_messaging: ^14.6.5
  shared_preferences: ^2.2.2
  uuid: ^4.1.0
  provider: ^6.0.5
  fl_chart: ^0.64.0
  intl: ^0.18.0
  flutter_local_notifications: ^16.1.0
  flutter_timezone: ^1.0.7
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lint: ^2.1.2

flutter:

  uses-material-design: true

  assets:
  - assets/images/phon.jpg
  - assets/icons/icon.jpg

  fonts:
    - family: IndieFlower
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf
